package covenant:memo-generator@1.0.0;

world memo-generator {
  import host:interfaces/logging@2.1.0;
  import host:interfaces/kv-store@2.1.0;
  import host:interfaces/signing@2.1.0;
  import host:interfaces/time@2.1.0;

  export contracts;
}

interface contracts {
  record generic-input {
    input: option<list<u8>>,
    user-profile: option<list<u8>>,
    context: option<list<u8>>,
  }

  generate-memo: func(req: generic-input) -> result<list<u8>, string>;
  verify-memo: func(req: generic-input) -> result<list<u8>, string>;
}
